Add HEADER.md file
opensearch-project/opensearch-clients pull request #35
Opened 2022-09-15 18:05 UTC by harshavamsi

Signed-off-by: Harsha Vamsi Kalluri <harshavamsi096@gmail.com>

### Description
Adds recommended license headers for every language.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-19 21:53 UTC, dblock requested changes
I’d like most of this content to go into .github and only client-specific things to be here. You can link back to that repo from wherever appropriate.

2022-09-19 21:53 UTC, dblock commented on HEADERS.md
> +### Automated License Headers' Checks
This is talking about plugins. I think it belongs in opensearch-plugins.

2022-09-19 21:53 UTC, dblock commented on HEADERS.md
> +### License Headers
This is generic for all repos in this project.

2022-10-05 16:36 UTC, harshavamsi commented
@dblock I've removed most of the content and linked back to .github's license text.

2022-10-05 18:12 UTC, dblock commented
So there's nothing client-specific anymore :) Do we need this file at all?

2022-10-27 22:12 UTC, harshavamsi commented
> So there's nothing client-specific anymore :) Do we need this file at all?

I don't think so :) Closing.

2022-10-27 22:12 UTC, closed without merging